2018-10-05 02:17:33 [root] WARNING: 重复处理：https://www.amazon.com/KobraTech-Cell-Phone-Tripod-Mount/dp/B06VXJMMQ3/ref=zg_bs_3347771_5?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:17:33 [root] WARNING: 重复处理：https://www.amazon.com/SUPON-Threaded-Compatible-Microphone-Motorcycle/dp/B00PICAE4C/ref=zg_bs_3347771_67?_encoding=UTF8&psc=1&refRID=Z083WPQ9CVB2FEMGMAZ3
2018-10-05 02:17:38 [root] WARNING: 重复处理：https://www.amazon.com/Sametop-Replacement-Adapter-Compatible-Session/dp/B0126KXDN2/ref=zg_bs_3347771_28?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:17:38 [root] WARNING: 重复处理：https://www.amazon.com/CamKix-replacement-Harness-compatible-Session/dp/B00PQ6B5SY/ref=zg_bs_3347771_30?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:17:40 [root] WARNING: 重复处理：https://www.amazon.com/GorillaPod-Premium-Flexible-Pro-Grade-Charcoal/dp/B074WG1ZTJ/ref=zg_bs_3347771_80?_encoding=UTF8&psc=1&refRID=Z083WPQ9CVB2FEMGMAZ3
2018-10-05 02:17:49 [root] WARNING: 重复处理：https://www.amazon.com/HME-Products-Ground-Trail-Camera/dp/B008IADWMW/ref=zg_bs_3347771_36?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:17:49 [root] WARNING: 重复处理：https://www.amazon.com/GoPro-Strap-QuickClip-Official-Mount/dp/B00F19PYR4/ref=zg_bs_3347771_8?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:17:57 [root] WARNING: 重复处理：https://www.amazon.com/Sametop-Backpack-Compatible-Session-Cameras/dp/B01BSE454S/ref=zg_bs_3347771_13?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:18:00 [root] WARNING: 重复处理：https://www.amazon.com/Dropcessories-Ceiling-Compatible-Wire-Free-Cameras/dp/B071YF3PZJ/ref=zg_bs_3347771_37?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:18:14 [root] WARNING: 重复处理：https://www.amazon.com/Compatible-Lightweight-Aluminum-Wireless-Smartphone/dp/B07DX56DJ8/ref=zg_bs_3347771_42?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:18:27 [root] WARNING: 重复处理：https://www.amazon.com/GoPro-Vented-Helmet-Strap-Official/dp/B002EF2200/ref=zg_bs_3347771_77?_encoding=UTF8&psc=1&refRID=Z083WPQ9CVB2FEMGMAZ3
2018-10-05 02:18:56 [root] WARNING: 重复处理：https://www.amazon.com/Rexing-Adhesive-Mounts-Dash-Cameras/dp/B014C1FDTU/ref=zg_bs_3347771_38?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:19:06 [root] WARNING: 重复处理：https://www.amazon.com/Anti-Theft-Security-Compatible-Weatherproof-Collar/dp/B07CCH1GVS/ref=zg_bs_3347771_24?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:19:07 [root] WARNING: 重复处理：https://www.amazon.com/GorillaPod-Professional-Ballhead-Mirrorless-Charcoal/dp/B074WG19MP/ref=zg_bs_3347771_69?_encoding=UTF8&psc=1&refRID=Z083WPQ9CVB2FEMGMAZ3
2018-10-05 02:19:16 [root] WARNING: 重复处理：https://www.amazon.com/Vktech-Black-Camera-Quick-Release/dp/B00G7IRCLE/ref=zg_bs_3347771_90?_encoding=UTF8&psc=1&refRID=Z083WPQ9CVB2FEMGMAZ3
2018-10-05 02:19:28 [root] WARNING: 重复处理：https://www.amazon.com/GorillaPod-Compact-Ballhead-Mirrorless-Charcoal/dp/B074WC9YKL/ref=zg_bs_3347771_3?_encoding=UTF8&psc=1&refRID=ZQ24JHN4ETA7837DCV39
2018-10-05 02:19:33 [root] WARNING: 重复处理：https://www.amazon.com/Rode-RodeLink-Wireless-Filmmaker-System/dp/B00TV90DX0/ref=zg_bs_196569011_44?_encoding=UTF8&psc=1&refRID=MDMHAK81S06G5JQS5MSZ
2018-10-05 02:19:41 [root] WARNING: 重复处理：https://www.amazon.com/SmallRig-Adjustable-Friction-Articulating-Monitor/dp/B076KDD8MY/ref=zg_bs_196569011_96?_encoding=UTF8&psc=1&refRID=5DFS8JBWXJBRZ5Q64P78
2018-10-05 02:19:42 [root] WARNING: 重复处理：https://www.amazon.com/OFFICIAL-stabilizer-Limited-Midnight-Smartphone/dp/B00S10KFTC/ref=zg_bs_196569011_18?_encoding=UTF8&psc=1&refRID=MDMHAK81S06G5JQS5MSZ
2018-10-05 02:19:58 [root] WARNING: 重复处理：https://www.amazon.com/Lavalier-Microphones-MAONO-Omnidirectional-Condenser/dp/B075H35NGN/ref=zg_bs_196569011_77?_encoding=UTF8&psc=1&refRID=5DFS8JBWXJBRZ5Q64P78
2018-10-05 02:20:07 [analysis_log] ERROR: add_Cart
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 280, in add_Cart
    timeout = 4
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)
2018-10-05 02:20:09 [root] WARNING: 重复处理：https://www.amazon.com/AmazonBasics-50-Inch-Lightweight-Tripod-SanDisk/dp/B077W49PF8/ref=zg_bs_196569011_88?_encoding=UTF8&psc=1&refRID=5DFS8JBWXJBRZ5Q64P78
2018-10-05 02:20:12 [analysis_log] ERROR: add_Cart
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 280, in add_Cart
    timeout = 4
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)
2018-10-05 02:20:18 [root] WARNING: 重复处理：https://www.amazon.com/BOYA-Lavalier-Microphone-Smartphones-Camcorders/dp/B00MRMU2HU/ref=zg_bs_196569011_53?_encoding=UTF8&psc=1&refRID=5DFS8JBWXJBRZ5Q64P78
2018-10-05 02:20:22 [root] WARNING: 重复处理：https://www.amazon.com/Movo-VXR10GY-Microphone-Windscreen-Smartphones/dp/B076X7VWYV/ref=zg_bs_196569011_82?_encoding=UTF8&psc=1&refRID=5DFS8JBWXJBRZ5Q64P78
2018-10-05 02:20:26 [root] WARNING: 重复处理：https://www.amazon.com/SGC-598-Photography-Interview-Microphone-Interface/dp/B00HE9G3UQ/ref=zg_bs_196569011_54?_encoding=UTF8&psc=1&refRID=5DFS8JBWXJBRZ5Q64P78
2018-10-05 02:21:04 [root] WARNING: 重复处理：https://www.amazon.com/Albott-Travel-Portable-Monopod-Flexible/dp/B01KT784OM/ref=zg_bs_196569011_19?_encoding=UTF8&psc=1&refRID=MDMHAK81S06G5JQS5MSZ
2018-10-05 02:21:28 [root] WARNING: 重复处理：https://www.amazon.com/Regetek-Professional-Adjustable-Camcorder-Cellphone/dp/B073WCL4NS/ref=zg_bs_196569011_27?_encoding=UTF8&psc=1&refRID=MDMHAK81S06G5JQS5MSZ
2018-10-05 02:21:31 [root] WARNING: 重复处理：https://www.amazon.com/CableCreation-5-PACK-Female-6-35mm-Adapter/dp/B01J33CP6G/ref=zg_bs_196569011_92?_encoding=UTF8&psc=1&refRID=5DFS8JBWXJBRZ5Q64P78
2018-10-05 02:21:48 [root] WARNING: 重复处理：https://www.amazon.com/Thunderbolt-Compatible-MacBook-Surface-Samsung/dp/B07CL2RHX5/ref=zg_bs_505106_86?_encoding=UTF8&psc=1&refRID=RX93BJ8AR15W95PD8J6C
2018-10-05 02:21:52 [analysis_log] ERROR: add_Cart
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 280, in add_Cart
    timeout = 4
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)
2018-10-05 02:21:59 [root] WARNING: 重复处理：https://www.amazon.com/AmazonBasics-High-Speed-Female-Extension-Cable/dp/B01D5H91KE/ref=zg_bs_505106_60?_encoding=UTF8&psc=1&refRID=RX93BJ8AR15W95PD8J6C
2018-10-05 02:22:07 [root] WARNING: 重复处理：https://www.amazon.com/HDMI-Cable-6ft-2-Pack-Compatible/dp/B06XP129CT/ref=zg_bs_505106_75?_encoding=UTF8&psc=1&refRID=RX93BJ8AR15W95PD8J6C
2018-10-05 02:22:21 [root] WARNING: 重复处理：https://www.amazon.com/AmazonBasics-High-Speed-Micro-HDMI-HDMI-Cable/dp/B014I8U33I/ref=zg_bs_505106_48?_encoding=UTF8&psc=1&refRID=2JAYWJQ7PYBPJWFAENHP
2018-10-05 02:22:22 [root] ERROR: start_Process
Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMAZONscrapy/AMAZONscrapy/pipelines.py", line 154, in process_item
    t.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
2018-10-05 02:22:27 [root] WARNING: 重复处理：https://www.amazon.com/UGREEN-Extension-Extender-Chromecast-Nintendo/dp/B00QV3THB8/ref=zg_bs_505106_32?_encoding=UTF8&psc=1&refRID=2JAYWJQ7PYBPJWFAENHP
2018-10-05 02:22:59 [root] WARNING: 重复处理：https://www.amazon.com/BlueRigger-Speed-Adapter-Cable-Meters/dp/B004S4R5CK/ref=zg_bs_505106_61?_encoding=UTF8&psc=1&refRID=RX93BJ8AR15W95PD8J6C
2018-10-05 02:23:00 [root] WARNING: 重复处理：https://www.amazon.com/AmazonBasics-High-Speed-Mini-HDMI-HDMI-Cable/dp/B014I8UAPE/ref=zg_bs_505106_92?_encoding=UTF8&psc=1&refRID=RX93BJ8AR15W95PD8J6C
2018-10-05 02:23:21 [root] WARNING: 重复处理：https://www.amazon.com/INGLY-Female-Extender-Convenient-Connection/dp/B01G09J686/ref=zg_bs_505106_88?_encoding=UTF8&psc=1&refRID=RX93BJ8AR15W95PD8J6C
2018-10-05 02:23:22 [root] WARNING: 重复处理：https://www.amazon.com/Cable-Supports-FullHD-Ethernet-KabelDirekt/dp/B00SVE6YF2/ref=zg_bs_505106_89?_encoding=UTF8&psc=1&refRID=RX93BJ8AR15W95PD8J6C
2018-10-05 02:23:25 [analysis_log] ERROR: add_Cart
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 280, in add_Cart
    timeout = 4
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)
2018-10-05 02:23:32 [root] WARNING: 重复处理：https://www.amazon.com/Vivitar-Professional-Filter-Accessory-18-55mm/dp/B00AE8EAW2/ref=zg_bs_7242007011_29?_encoding=UTF8&psc=1&refRID=8KDV2QVJAK6Y3K9BM214
2018-10-05 02:23:33 [root] WARNING: 重复处理：https://www.amazon.com/Altura-Essential-Accessory-Bundle-Fisheye/dp/B003ZW316U/ref=zg_bs_7242007011_52?_encoding=UTF8&psc=1&refRID=DTPN25NYYAHKNH8HYQ81
2018-10-05 02:25:00 [root] WARNING: 重复处理：https://www.amazon.com/Accessories-Cyber-shot-DSC-HX300-Carrying-Protectors/dp/B00BYFKVZ4/ref=zg_bs_7242007011_67?_encoding=UTF8&psc=1&refRID=DTPN25NYYAHKNH8HYQ81
2018-10-05 02:25:24 [root] WARNING: 重复处理：https://www.amazon.com/Iextreme-Action-Accessories-Carrying-Octopus/dp/B0169T94KC/ref=zg_bs_7242007011_5?_encoding=UTF8&psc=1&refRID=8KDV2QVJAK6Y3K9BM214
2018-10-05 02:25:24 [analysis_log] ERROR: add_Cart
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 280, in add_Cart
    timeout = 4
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)
2018-10-05 02:25:47 [root] WARNING: 重复处理：https://www.amazon.com/Altura-Photo-Professional-Photography-Polarizer/dp/B0083WYE7C/ref=zg_bs_7242007011_41?_encoding=UTF8&psc=1&refRID=8KDV2QVJAK6Y3K9BM214
2018-10-05 02:26:10 [root] WARNING: 重复处理：https://www.amazon.com/Bonacell-2000mAh-Replacement-EN-EL15-Battery/dp/B078XBG9JQ/ref=zg_bs_7242007011_30?_encoding=UTF8&psc=1&refRID=8KDV2QVJAK6Y3K9BM214
2018-10-05 02:26:14 [root] WARNING: 重复处理：https://www.amazon.com/RayHom-Outdoor-Accessory-Lightdow-Carrying/dp/B06XSMSL5J/ref=zg_bs_7242007011_3?_encoding=UTF8&psc=1&refRID=8KDV2QVJAK6Y3K9BM214
2018-10-05 02:26:53 [root] WARNING: 重复处理：https://www.amazon.com/Halloween-Costumes-Pervobs-Sleeves-Dresses/dp/B07GSYJ33H/ref=zg_bs_3345801_83?_encoding=UTF8&refRID=NJEXN23SSFJCCZEZGXZ3
2018-10-05 02:27:03 [root] WARNING: 重复处理：https://www.amazon.com/Halloween-Costumes-Pervobs-Pumpkin-Printing/dp/B07GSWNBZN/ref=zg_bs_3345801_19?_encoding=UTF8&refRID=W330NTZNR83V3DQ9X72X
2018-10-05 02:27:20 [root] WARNING: 重复处理：https://www.amazon.com/FashionNew-listed-TOTOD-Patchwork-Pullover/dp/B07GDJJQFV/ref=zg_bs_3345801_31?_encoding=UTF8&refRID=W330NTZNR83V3DQ9X72X
2018-10-05 02:27:42 [root] WARNING: 重复处理：https://www.amazon.com/SMALLE-Clearance-Sweatshirts-Sweatshirt-Pullover/dp/B07H2BNFR8/ref=zg_bs_3345801_7?_encoding=UTF8&refRID=W330NTZNR83V3DQ9X72X
2018-10-05 02:28:40 [root] WARNING: 重复处理：https://www.amazon.com/Clearance-Tankini-Swimdress-Swimwear-Swimsuit/dp/B07F285665/ref=zg_bs_3345801_6?_encoding=UTF8&refRID=W330NTZNR83V3DQ9X72X
2018-10-05 02:28:41 [root] WARNING: 重复处理：https://www.amazon.com/Kowa-Long-Eye-Relief-Eyepiece/dp/B00RHGHUYO/ref=zg_bs_3345801_82?_encoding=UTF8&refRID=NJEXN23SSFJCCZEZGXZ3
2018-10-05 02:29:08 [analysis_log] ERROR: add_Cart
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 280, in add_Cart
    timeout = 20
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)
2018-10-05 02:29:11 [root] WARNING: 重复处理：https://www.amazon.com/SMALLE-Clearance-Casual-Sleeve-Hoodie/dp/B07GYVGJKG/ref=zg_bs_3345801_66?_encoding=UTF8&refRID=NJEXN23SSFJCCZEZGXZ3
2018-10-05 02:29:27 [root] WARNING: 重复处理：https://www.amazon.com/Ulanzi-Ultra-Bright-Video-Light/dp/B0757KCWGW/ref=zg_bs_7161086011_36?_encoding=UTF8&psc=1&refRID=CB8RD7X9RK2569JKACKN
2018-10-05 02:29:31 [root] WARNING: 重复处理：https://www.amazon.com/Neewer-Photography-Relfectors-Softboxes-Backgrounds/dp/B00K69A0QY/ref=zg_bs_7161086011_39?_encoding=UTF8&psc=1&refRID=CB8RD7X9RK2569JKACKN
2018-10-05 02:29:54 [root] WARNING: 重复处理：https://www.amazon.com/ESDDI-Photography-Adjustable-Background-Continuous/dp/B078K6ZNV5/ref=zg_bs_7161086011_97?_encoding=UTF8&psc=1&refRID=98TN9600TFNXRNH5A154
2018-10-05 02:29:58 [root] WARNING: 重复处理：https://www.amazon.com/Newborn-Photography-Basket-Filler-Posing/dp/B01ENC2ASU/ref=zg_bs_7161086011_69?_encoding=UTF8&psc=1&refRID=98TN9600TFNXRNH5A154
2018-10-05 02:30:39 [root] WARNING: 重复处理：https://www.amazon.com/Dancina-Sparkle-Tulle-Skirt-Girls/dp/B07FY15YS2/ref=zg_bs_7161086011_56?_encoding=UTF8&refRID=98TN9600TFNXRNH5A154
2018-10-05 02:30:42 [root] WARNING: 重复处理：https://www.amazon.com/Photography-ESDDI-Portable-Jewellery-Advertising/dp/B07C4M84FS/ref=zg_bs_7161086011_92?_encoding=UTF8&psc=1&refRID=98TN9600TFNXRNH5A154
2018-10-05 02:30:52 [analysis_log] ERROR: add_Cart
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 280, in add_Cart
    timeout = 20
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)
2018-10-05 02:30:57 [analysis_log] ERROR: add_Cart
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 280, in add_Cart
    timeout = 20
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)
2018-10-05 02:31:01 [root] WARNING: 重复处理：https://www.amazon.com/Oksale-Womens-Woolen-Cardigan-Sleeveless/dp/B07H1CYMBZ/ref=zg_bs_7161086011_10?_encoding=UTF8&refRID=CB8RD7X9RK2569JKACKN
2018-10-05 02:31:03 [root] WARNING: 重复处理：https://www.amazon.com/Fujifilm-Instax-Mini-Groovy-Case/dp/B06XW9SRTV/ref=zg_bs_172437_51?_encoding=UTF8&psc=1&refRID=SEXTYGGY5CX45WBM2F0E
2018-10-05 02:31:13 [root] WARNING: 重复处理：https://www.amazon.com/Digital-Connected-Protective-Carrying-Hermitshell/dp/B01D2ZQA9E/ref=zg_bs_172437_16?_encoding=UTF8&psc=1&refRID=WTY6SRPSFJHF88V0G4EZ
2018-10-05 02:31:40 [analysis_log] ERROR: add_Cart
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 280, in add_Cart
    timeout = 20
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)
2018-10-05 02:31:41 [analysis_log] ERROR: add_Cart
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 280, in add_Cart
    timeout = 20
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.amazon.com', port=443): Read timed out. (read timeout=4)
2018-10-05 02:31:45 [root] WARNING: 重复处理：https://www.amazon.com/OP-TECH-USA-Utility-Connector/dp/B000IN3RUE/ref=zg_bs_172437_19?_encoding=UTF8&psc=1&refRID=WTY6SRPSFJHF88V0G4EZ
2018-10-05 02:31:53 [root] WARNING: 重复处理：https://www.amazon.com/LTGEM-Polaroid-Instant-Digital-Camera/dp/B06Y4M6DT9/ref=zg_bs_172437_64?_encoding=UTF8&psc=1&refRID=SEXTYGGY5CX45WBM2F0E
2018-10-05 02:32:00 [root] WARNING: 重复处理：https://www.amazon.com/Travel-DSC-W830-Digital-Camera-Aenllosi/dp/B0794SR8MD/ref=zg_bs_172437_94?_encoding=UTF8&refRID=SEXTYGGY5CX45WBM2F0E
2018-10-05 02:32:11 [root] ERROR: start_Process
Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMAZONscrapy/AMAZONscrapy/pipelines.py", line 154, in process_item
    t.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
2018-10-05 02:32:27 [root] WARNING: 重复处理：https://www.amazon.com/OP-TECH-USA-6501082-Double/dp/B004N622H6/ref=zg_bs_172437_87?_encoding=UTF8&psc=1&refRID=SEXTYGGY5CX45WBM2F0E
2018-10-05 02:32:36 [root] WARNING: 重复处理：https://www.amazon.com/Altura-Photo-Backpack-Mirrorless-Cameras/dp/B00PV0IEDY/ref=zg_bs_172437_11?_encoding=UTF8&psc=1&refRID=WTY6SRPSFJHF88V0G4EZ
2018-10-05 02:32:39 [root] WARNING: 重复处理：https://www.amazon.com/Sony-LCSU21-Carrying-Cyber-Shot-Cameras/dp/B00B06EON2/ref=zg_bs_172437_92?_encoding=UTF8&psc=1&refRID=SEXTYGGY5CX45WBM2F0E
2018-10-05 02:32:55 [root] WARNING: 重复处理：https://www.amazon.com/AmazonBasics-Medium-DSLR-Gadget-Interior/dp/B00CF7E0R0/ref=zg_bs_172437_56?_encoding=UTF8&psc=1&refRID=SEXTYGGY5CX45WBM2F0E
2018-10-05 02:33:10 [root] WARNING: 重复处理：https://www.amazon.com/Lowpricenice-52mm-Universal-Snap-Lens/dp/B003LTA3GS/ref=zg_bs_525898_53?_encoding=UTF8&psc=1&refRID=2Q8D3557HYQJN0PTZ5KA
2018-10-05 02:33:24 [root] WARNING: 重复处理：https://www.amazon.com/Snap-replaces-Canon-Lenses-Keeper/dp/B01MXIB1RR/ref=zg_bs_525898_52?_encoding=UTF8&psc=1&refRID=2Q8D3557HYQJN0PTZ5KA
2018-10-05 02:33:26 [root] WARNING: 重复处理：https://www.amazon.com/Replacement-Altura-Photo-18-135mm-3-5-5-6/dp/B0045FLMIA/ref=zg_bs_525898_44?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:33:38 [root] WARNING: 重复处理：https://www.amazon.com/S-ZONE-Waterproof-Camera-Insert-Olympus/dp/B071JRJRQ6/ref=zg_bs_172437_65?_encoding=UTF8&refRID=SEXTYGGY5CX45WBM2F0E
2018-10-05 02:33:38 [root] WARNING: 重复处理：https://www.amazon.com/Xenvo-iPhone-Camera-Lens-Clip/dp/B01A6D2JVI/ref=zg_bs_525898_2?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:33:46 [root] WARNING: 重复处理：https://www.amazon.com/Center-Pinch-Strong-Springs-Recycled-Plastic/dp/B01J6ZKJT6/ref=zg_bs_525898_49?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:33:47 [root] WARNING: 重复处理：https://www.amazon.com/2-Pack-JJC-Mount-Cameras-Minolta/dp/B06XQ1FJPT/ref=zg_bs_525898_93?_encoding=UTF8&psc=1&refRID=2Q8D3557HYQJN0PTZ5KA
2018-10-05 02:33:58 [root] WARNING: 重复处理：https://www.amazon.com/Snap-Replaces-Canon-Lenses-Keeper/dp/B01LXM68ON/ref=zg_bs_525898_25?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:34:05 [root] WARNING: 重复处理：https://www.amazon.com/ChromLives-Lens-Cap-Leash-Panasonic/dp/B0731H4WND/ref=zg_bs_525898_30?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:34:07 [root] WARNING: 重复处理：https://www.amazon.com/Center-Pinch-Strong-Springs-Recycled-Plastic/dp/B01J6ZKBXA/ref=zg_bs_525898_29?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:34:13 [root] WARNING: 重复处理：https://www.amazon.com/Generic-58mm-Lens-Canon-Replaces/dp/B00G3SAYS6/ref=zg_bs_525898_16?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:34:16 [root] WARNING: 重复处理：https://www.amazon.com/Snap-Replaces-Canon-Lenses-Keeper/dp/B01LXAENNT/ref=zg_bs_525898_70?_encoding=UTF8&psc=1&refRID=2Q8D3557HYQJN0PTZ5KA
2018-10-05 02:34:25 [root] WARNING: 重复处理：https://www.amazon.com/Commlite-CM-EF-EOS-Electronic-Auto-Focus-Adapter-Canon/dp/B0788PDN1S/ref=zg_bs_525898_41?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:34:32 [root] WARNING: 重复处理：https://www.amazon.com/waka-Camera-Keeper-Microfiber-Cleaning/dp/B01DK0FVJ6/ref=zg_bs_525898_27?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:34:34 [root] WARNING: 重复处理：https://www.amazon.com/Center-Pinch-Strong-Springs-Recycled-Plastic/dp/B01J6ZKOSM/ref=zg_bs_525898_50?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:34:35 [root] WARNING: 重复处理：https://www.amazon.com/Lens-Rear-Screw-Mount-Packs/dp/B00G1O7ZO8/ref=zg_bs_525898_84?_encoding=UTF8&psc=1&refRID=2Q8D3557HYQJN0PTZ5KA
2018-10-05 02:34:39 [root] WARNING: 重复处理：https://www.amazon.com/Center-Pinch-Strong-Springs-Recycled-Plastic/dp/B01J6ZKM0M/ref=zg_bs_525898_76?_encoding=UTF8&psc=1&refRID=2Q8D3557HYQJN0PTZ5KA
2018-10-05 02:34:40 [root] WARNING: 重复处理：https://www.amazon.com/JJC-Reversible-Dedicated-3-5-5-6G-10-100mm/dp/B071CT7YFB/ref=zg_bs_525898_78?_encoding=UTF8&psc=1&refRID=2Q8D3557HYQJN0PTZ5KA
2018-10-05 02:34:50 [root] WARNING: 重复处理：https://www.amazon.com/Nikon-HB-32-Flower-18-70mm-Nikkor/dp/B0001WE6U2/ref=zg_bs_525898_95?_encoding=UTF8&psc=1&refRID=2Q8D3557HYQJN0PTZ5KA
2018-10-05 02:34:56 [root] WARNING: 重复处理：https://www.amazon.com/Canon-E-52-II-Lens-Cap/dp/B008NFWCH8/ref=zg_bs_525898_100?_encoding=UTF8&psc=1&refRID=2Q8D3557HYQJN0PTZ5KA
2018-10-05 02:34:58 [root] WARNING: 重复处理：https://www.amazon.com/Replacement-Altura-Photo-18-55mm-3-5-5-6/dp/B01AAYZQNQ/ref=zg_bs_525898_45?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:35:14 [root] WARNING: 重复处理：https://www.amazon.com/PCS-58mm-Lens-Canon-Replaces/dp/B01HXQ968A/ref=zg_bs_525898_3?_encoding=UTF8&psc=1&refRID=392YX49C2W04KSJC92VT
2018-10-05 02:35:27 [root] WARNING: 重复处理：https://www.amazon.com/Microfiber-Cleaning-Eyeglasses-Glasses-Screen/dp/B01HYKQR8W/ref=zg_bs_172426_11?_encoding=UTF8&psc=1&refRID=6S8N1QXHJDG04A3XTRYJ
2018-10-05 02:35:29 [root] WARNING: 重复处理：https://www.amazon.com/HTTX-Microfiber-Cleaning-Tablets-Spectacles/dp/B01GO244R2/ref=zg_bs_172426_39?_encoding=UTF8&psc=1&refRID=6S8N1QXHJDG04A3XTRYJ
2018-10-05 02:35:30 [root] WARNING: 重复处理：https://www.amazon.com/FOTGA-Professional-Cleaning-Keyboard-Telescope/dp/B01E9W4U9Q/ref=zg_bs_172426_54?_encoding=UTF8&psc=1&refRID=G0AAHS2Q6HFS7YZM54XV
2018-10-05 02:35:38 [root] WARNING: 重复处理：https://www.amazon.com/MagicFiber-Microfiber-Cleaning-Cloths-PACK/dp/B0050R68LS/ref=zg_bs_172426_6?_encoding=UTF8&psc=1&refRID=6S8N1QXHJDG04A3XTRYJ
2018-10-05 02:35:39 [root] WARNING: 重复处理：https://www.amazon.com/Photographic-Solutions-Eclipse-Cleaner-Sensors/dp/B00OPB0AB4/ref=zg_bs_172426_25?_encoding=UTF8&psc=1&refRID=6S8N1QXHJDG04A3XTRYJ
2018-10-05 02:35:46 [root] WARNING: 重复处理：https://www.amazon.com/Altura-Photo-Professional-Cleaning-Cameras/dp/B01JQQCTQQ/ref=zg_bs_172426_27?_encoding=UTF8&psc=1&refRID=6S8N1QXHJDG04A3XTRYJ
2018-10-05 02:36:02 [analysis_log] ERROR: into_Sellers_list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 555, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 753, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 230, in connect
    self._tunnel()
  File "/usr/lib/python3.5/http/client.py", line 827, in _tunnel
    (version, code, message) = response._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.amazon.com', port=443): Max retries exceeded with url: /gp/offer-listing/B013UBXVI8/ref=dp_olp_new_mbc?ie=UTF8&condition=new (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 300, in into_Sellers_list
    sellers_list_responses = myrequest_get(url=sellers_list_url,headers=headers)
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 256, in myrequest_get
    timeout=20
  File "/usr/lib/python3/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.amazon.com', port=443): Max retries exceeded with url: /gp/offer-listing/B013UBXVI8/ref=dp_olp_new_mbc?ie=UTF8&condition=new (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2018-10-05 02:36:05 [analysis_log] ERROR: into_Sellers_list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 555, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 753, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 230, in connect
    self._tunnel()
  File "/usr/lib/python3.5/http/client.py", line 827, in _tunnel
    (version, code, message) = response._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.amazon.com', port=443): Max retries exceeded with url: /gp/offer-listing/B013UBXVI8/ref=dp_olp_new_mbc?ie=UTF8&condition=new (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 300, in into_Sellers_list
    sellers_list_responses = myrequest_get(url=sellers_list_url,headers=headers)
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 256, in myrequest_get
    timeout=20
  File "/usr/lib/python3/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.amazon.com', port=443): Max retries exceeded with url: /gp/offer-listing/B013UBXVI8/ref=dp_olp_new_mbc?ie=UTF8&condition=new (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2018-10-05 02:36:05 [analysis_log] ERROR: sellers_list_responses
Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/USA_analysis.py", line 1067, in Available
    sellers_list_responses = into_Sellers_list(sellers_list_url)
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/analysis_request_header.py", line 305, in into_Sellers_list
    return sellers_list_responses
UnboundLocalError: local variable 'sellers_list_responses' referenced before assignment
2018-10-05 02:36:05 [analysis_log] ERROR: USA_USA_second_Analysis
Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/use_analysis.py", line 79, in USA_analysis
    USA_second_Analysis(ASIN=ASIN,stock=Stock,sellers_list_url=sellers_list_url,product_info=product_info,offerListingID=offerListingID)
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/USA_analysis.py", line 1198, in USA_second_Analysis
    usa_second_product_obj.Available(sellers_list_url=sellers_list_url,ASIN=ASIN)
  File "/root/Xuggest_scrapy/AMA_ANALYSIS/USA_analysis.py", line 1072, in Available
    etree_html = etree.HTML(sellers_list_responses)
UnboundLocalError: local variable 'sellers_list_responses' referenced before assignment
2018-10-05 02:36:10 [root] WARNING: 重复处理：https://www.amazon.com/Camera-Lens-Cleaning-Kit-Individually/dp/B06Y65NXKR/ref=zg_bs_172426_37?_encoding=UTF8&psc=1&refRID=6S8N1QXHJDG04A3XTRYJ
2018-10-05 02:36:12 [root] WARNING: 重复处理：https://www.amazon.com/D-SLR-Sensor-Cleaning-Brush-Sensors/dp/B000LQQQZQ/ref=zg_bs_172426_88?_encoding=UTF8&psc=1&refRID=G0AAHS2Q6HFS7YZM54XV
2018-10-05 02:36:37 [root] WARNING: 重复处理：https://www.amazon.com/VSGO-Mirrorless-Panasonic-Olympus-DDR-12/dp/B00ZHSNSEK/ref=zg_bs_172426_72?_encoding=UTF8&psc=1&refRID=G0AAHS2Q6HFS7YZM54XV
2018-10-05 02:36:43 [root] WARNING: 重复处理：https://www.amazon.com/Professional-Cleaning-waterproof-non-toxic-alcohol-free/dp/B071ZH7LFX/ref=zg_bs_172426_43?_encoding=UTF8&psc=1&refRID=6S8N1QXHJDG04A3XTRYJ
2018-10-05 02:36:49 [root] WARNING: 重复处理：https://www.amazon.com/Most-Amazing-Microfiber-Cleaning-Cloths/dp/B00GMRCAC6/ref=zg_bs_172426_36?_encoding=UTF8&psc=1&refRID=6S8N1QXHJDG04A3XTRYJ
2018-10-05 02:36:49 [root] WARNING: 重复处理：https://www.amazon.com/Hapurs-Cleaning-Accessories-Remover-Keyboard/dp/B013JGKE0C/ref=zg_bs_172426_67?_encoding=UTF8&psc=1&refRID=G0AAHS2Q6HFS7YZM54XV
2018-10-05 02:37:31 [root] WARNING: 重复处理：https://www.amazon.com/Camera-Tripod-Patekfly-Flexible-Android/dp/B078BQ2MKY/ref=zg_bs_499306_53?_encoding=UTF8&psc=1&refRID=RVP7TSDY1JSBRFXNCHCE
2018-10-05 02:37:31 [root] WARNING: 重复处理：https://www.amazon.com/Bosch-BT150-Compact-Extendable-Adjustable/dp/B00SIL5O36/ref=zg_bs_499306_35?_encoding=UTF8&psc=1&refRID=V3PNT3FNQS1DX0A4B2WS
2018-10-05 02:37:39 [root] WARNING: 重复处理：https://www.amazon.com/Adjustable-Flexible-Wireless-Universal-Compatible/dp/B0746C1HHN/ref=zg_bs_499306_21?_encoding=UTF8&psc=1&refRID=V3PNT3FNQS1DX0A4B2WS
2018-10-05 02:37:40 [root] WARNING: 重复处理：https://www.amazon.com/Regetek-Aluminum-Adjustable-Portable-Camcorder/dp/B073WC9R14/ref=zg_bs_499306_37?_encoding=UTF8&psc=1&refRID=V3PNT3FNQS1DX0A4B2WS
2018-10-05 02:37:49 [root] WARNING: 重复处理：https://www.amazon.com/SMILEPOWO-Lightweight-Universal-Smartphone-Adapter/dp/B077CYXM81/ref=zg_bs_499306_34?_encoding=UTF8&psc=1&refRID=V3PNT3FNQS1DX0A4B2WS
2018-10-05 02:37:56 [root] WARNING: 重复处理：https://www.amazon.com/BOG-POD-SSC-Super-Steady-Tripod/dp/B004XV1SLC/ref=zg_bs_499306_56?_encoding=UTF8&psc=1&refRID=RVP7TSDY1JSBRFXNCHCE
2018-10-05 02:38:19 [root] WARNING: 重复处理：https://www.amazon.com/Paladinz-Lightweight-Smartphone-Cellphone-Bluetooth/dp/B0731LTM1Q/ref=zg_bs_499306_39?_encoding=UTF8&psc=1&refRID=V3PNT3FNQS1DX0A4B2WS
2018-10-05 02:38:23 [root] WARNING: 重复处理：https://www.amazon.com/Flexible-Tripod-UBeesize-Smartphone-Compatible/dp/B077PNS1L1/ref=zg_bs_499306_12?_encoding=UTF8&psc=1&refRID=V3PNT3FNQS1DX0A4B2WS
2018-10-05 02:38:27 [root] WARNING: 重复处理：https://www.amazon.com/iGadgitz-Lightweight-Stabilizer-Digital-Camcorder/dp/B01BMFXNQE/ref=zg_bs_499306_38?_encoding=UTF8&psc=1&refRID=V3PNT3FNQS1DX0A4B2WS
2018-10-05 02:38:46 [root] WARNING: 重复处理：https://www.amazon.com/Sabrent-Flexible-standard-included-GP-TRPD/dp/B017XSJZL6/ref=zg_bs_499306_24?_encoding=UTF8&psc=1&refRID=V3PNT3FNQS1DX0A4B2WS
2018-10-05 02:39:05 [root] WARNING: 重复处理：https://www.amazon.com/Tripod-UBeesize-Universal-Lightweight-Compatible/dp/B0739KQJJR/ref=zg_bs_499306_61?_encoding=UTF8&psc=1&refRID=RVP7TSDY1JSBRFXNCHCE
2018-10-05 02:39:26 [root] WARNING: 重复处理：https://www.amazon.com/Flexible-Travel-Android-Smartphone-Vlogging/dp/B07D837TWB/ref=zg_bs_499306_31?_encoding=UTF8&psc=1&refRID=V3PNT3FNQS1DX0A4B2WS
2018-10-05 02:39:32 [root] WARNING: 重复处理：https://www.amazon.com/Manfrotto-MKCOMPACTACN-BK-Compact-Action-Tripod/dp/B00L6F16L0/ref=zg_bs_499306_76?_encoding=UTF8&psc=1&refRID=RVP7TSDY1JSBRFXNCHCE
2018-10-05 02:39:39 [root] WARNING: 重复处理：https://www.amazon.com/Sunmns-Computer-Powershot-Digital-Camera/dp/B073TSMLNF/ref=zg_bs_14015081_54?_encoding=UTF8&psc=1&refRID=EX5XKZ1EBX4B3ZE0TZYN
2018-10-05 02:40:05 [root] WARNING: 重复处理：https://www.amazon.com/Weatherproof-25ft-7-6m-Cable-Compatible/dp/B07FJLB9ZT/ref=zg_bs_14015081_12?_encoding=UTF8&psc=1&refRID=JNKQFJPB7N3N8VC13KWJ
2018-10-05 02:40:07 [root] WARNING: 重复处理：https://www.amazon.com/BOOTOO-TECH-Lightning-Reader-Adapter/dp/B07DB5432R/ref=zg_bs_14015081_29?_encoding=UTF8&psc=1&refRID=JNKQFJPB7N3N8VC13KWJ
2018-10-05 02:40:18 [root] WARNING: 重复处理：https://www.amazon.com/BRENDAZ-Mini-B-Cameras-Replacement-UC-E16/dp/B0758VPF9H/ref=zg_bs_14015081_41?_encoding=UTF8&psc=1&refRID=JNKQFJPB7N3N8VC13KWJ
2018-10-05 02:40:19 [root] WARNING: 重复处理：https://www.amazon.com/SIKAMI-Gopro-Black-Cable-Charging/dp/B077BCNK8D/ref=zg_bs_14015081_62?_encoding=UTF8&psc=1&refRID=EX5XKZ1EBX4B3ZE0TZYN
2018-10-05 02:40:23 [root] WARNING: 重复处理：https://www.amazon.com/IFC-500U-Compatible-Cable-Digital-Camera/dp/B00ZAWK78I/ref=zg_bs_14015081_58?_encoding=UTF8&psc=1&refRID=EX5XKZ1EBX4B3ZE0TZYN
2018-10-05 02:40:33 [root] WARNING: 重复处理：https://www.amazon.com/VariZoom-VZ-AV-LANC-Audio-Converter/dp/B003P9VN86/ref=zg_bs_14015081_56?_encoding=UTF8&psc=1&refRID=EX5XKZ1EBX4B3ZE0TZYN
2018-10-05 02:40:38 [root] WARNING: 重复处理：https://www.amazon.com/GOBEAUTY-Protector-iPhone-Winder-Accessory/dp/B07GJJRSM9/ref=zg_bs_14015081_45?_encoding=UTF8&refRID=JNKQFJPB7N3N8VC13KWJ
2018-10-05 02:40:53 [root] WARNING: 重复处理：https://www.amazon.com/Cable-Powershot-Digital-Camera-computer/dp/B01D2312YO/ref=zg_bs_14015081_3?_encoding=UTF8&psc=1&refRID=JNKQFJPB7N3N8VC13KWJ
2018-10-05 02:41:18 [root] WARNING: 重复处理：https://www.amazon.com/Weatherproof-1-8m-Cable-Compatible-Arlo/dp/B07F9M2J63/ref=zg_bs_14015081_26?_encoding=UTF8&psc=1&refRID=JNKQFJPB7N3N8VC13KWJ
2018-10-05 02:41:34 [root] WARNING: 重复处理：https://www.amazon.com/POPMAS-Charging-Resistance-Thickness-Security/dp/B077M5DV8R/ref=zg_bs_14015081_16?_encoding=UTF8&psc=1&refRID=JNKQFJPB7N3N8VC13KWJ
2018-10-05 02:41:35 [root] ERROR: start_Process
Traceback (most recent call last):
  File "/root/Xuggest_scrapy/AMAZONscrapy/AMAZONscrapy/pipelines.py", line 154, in process_item
    t.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
2018-10-05 02:41:39 [root] WARNING: 重复处理：https://www.amazon.com/SN-RIGGOR-Replacement-UC-E16-Battery-Charger/dp/B01M2Z90T9/ref=zg_bs_14015081_34?_encoding=UTF8&psc=1&refRID=JNKQFJPB7N3N8VC13KWJ
2018-10-05 02:41:42 [root] WARNING: 重复处理：https://www.amazon.com/Cable-Powershot-Digital-Camera-computer/dp/B01D23151E/ref=zg_bs_14015081_88?_encoding=UTF8&psc=1&refRID=EX5XKZ1EBX4B3ZE0TZYN
2018-10-05 02:42:10 [root] WARNING: 重复处理：https://www.amazon.com/GoPro-Battery-Charger-HERO6-Rechargeable/dp/B079W83HNJ/ref=zg_bs_13535371_66?_encoding=UTF8&psc=1&refRID=0VV7Y3MMFMFS5D7C8WYQ
2018-10-05 02:42:19 [root] WARNING: 重复处理：https://www.amazon.com/Sony-NP-FW50-Lithium-Ion-1020mAh-Rechargeable/dp/B003OBUJIK/ref=zg_bs_13535371_76?_encoding=UTF8&psc=1&refRID=0VV7Y3MMFMFS5D7C8WYQ
2018-10-05 02:42:20 [root] WARNING: 重复处理：https://www.amazon.com/Wasabi-Power-Battery-Charger-Fujifilm/dp/B06VVGY5KW/ref=zg_bs_13535371_78?_encoding=UTF8&psc=1&refRID=0VV7Y3MMFMFS5D7C8WYQ
2018-10-05 02:42:54 [root] WARNING: 重复处理：https://www.amazon.com/NP-F550-RAVPower-Battery-CCD-SC55-Replacement/dp/B0761SH551/ref=zg_bs_13535371_56?_encoding=UTF8&psc=1&refRID=0VV7Y3MMFMFS5D7C8WYQ
2018-10-05 02:43:02 [root] WARNING: 重复处理：https://www.amazon.com/Tenergy-Performance-Batteries-Flashlight-Replacement/dp/B003EOMVX8/ref=zg_bs_13535371_90?_encoding=UTF8&psc=1&refRID=0VV7Y3MMFMFS5D7C8WYQ
2018-10-05 02:43:11 [root] WARNING: 重复处理：https://www.amazon.com/EN-EL15-Powerextra-batteries-Battery-Compatible/dp/B06XXFHCHB/ref=zg_bs_13535371_80?_encoding=UTF8&psc=1&refRID=0VV7Y3MMFMFS5D7C8WYQ
2018-10-05 02:43:16 [root] WARNING: 重复处理：https://www.amazon.com/DSTE-NP-F550-Sony-CCD-RV100-CCD-RV200/dp/B00CPYXQ2S/ref=zg_bs_13535371_82?_encoding=UTF8&psc=1&refRID=0VV7Y3MMFMFS5D7C8WYQ
2018-10-05 02:43:20 [root] WARNING: 重复处理：https://www.amazon.com/GoPro-Rechargeable-Battery-Official-Accessory/dp/B00NIYNU66/ref=zg_bs_13535371_75?_encoding=UTF8&psc=1&refRID=0VV7Y3MMFMFS5D7C8WYQ
